### ISSUE TITLE
Updated TODO

### ISSUE THREAD

**Issue by akielaries** [akielaries/openGPMP#117]
Generic issue for keeping track of some TODOs 

* Overall optimization. So far the linear algebra module's matrix-matrix operations contain an optimized kernel for SSE ISAs. I want to add some optimizations in other modules of this project
  - [ ] For matrix and vector operations add optimized assembly kernels for AVX / AVX2 ISAs and verify compatibility with SSE2 ISAs
  - [ ] Make use of the matrix / vector optimizations in the machine learning module
  - [ ] Beyond matrix / vector operations target optimization in the entire linear algebra module
  - [ ] Explore how to optimize the number theory module as well and what this could possibly look like
  - [ ] More areas but the above will suffice for now....
